# -*- coding: utf-8 -*-
"""Rain-pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N05qPjlq7UvMuGiHNMfPT1W2EOJVLmJk
"""

import pandas as pd
import numpy as np

data= pd.read_csv('/content/austin_weather.csv')

data= data.drop(['Events','Date','SeaLevelPressureHighInches','SeaLevelPressureLowInches'],axis=1)

data=data.replace('T',0.0)
data= data.replace('-',0.0)

data.to_csv('/content/austin_weather.csv')

import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

data= pd.read_csv('/content/austin_weather.csv')
X= data.drop(['PrecipitationSumInches'],axis=1)
Y=data['PrecipitationSumInches']
X= Y.values.reshape(-1,1)

day=798
days=[i for i in range(Y.size)]

clf=LinearRegression() #train the classifier with our input data
clf.fit(X,Y)

inp = np.array([[74], [60], [45], [67], [49], [43], [33], [45],
                [57], [29.68], [10], [7], [2], [0], [20], [4], [31]])
inp= inp.reshape(-1,1)
print('The precipitation in inches for the output is:',clf.predict(inp))


print("The precipitation trend graph: ")
plt.scatter(days, Y, color='b')
plt.scatter(days[day],Y[day],color='r')
plt.title("precipitation level")
plt.xlabel("Days")
plt.ylabel("Precipitation in inches")

plt.show()

x_vis = X.filter(['TempAvgF', 'DewPointAvgF', 'HumidityAvgPercent','SeaLevelPressureAvgInches', 'VisibilityAvgMiles','WindAvgMPH'], axis=1)

print("Precipitation vs selected attributes graph:")

for i in range(x_vis.columns.size):
  plt.subplot(3,2,i+1)
  plt.scatter(days,x_vis[x_vis.columns.values[i][:100]],
              color='b')
  plt.scatter(days[day],
                x_vis[x_vis.columns.values[i]][day],
                color='r')
  plt.title(x_vis.columns.values[i])

plt.show()